In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv('loan_approval_dataset.csv')
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [39]:
df_onehot = pd.get_dummies(df)
df_onehot.drop(columns=["loan_status_ Rejected", "self_employed_ Yes", "education_ Not Graduate"], inplace=True)
df_onehot.head()

,load_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,education_ Graduate,self_employed_ No,loan_status_ Approved
0,1,2,9600000,29900000,12,778,2400000,17600000,22700000,8000000,True,True,True
1,2,0,4100000,12200000,8,417,2700000,2200000,8800000,3300000,False,False,False
2,3,3,9100000,29700000,20,506,7100000,4500000,33300000,12800000,True,True,False
3,4,3,8200000,30700000,8,467,18200000,3300000,23300000,7900000,True,True,False
4,5,5,9800000,24200000,20,382,12400000,8200000,29400000,5000000,False,False,False

In [41]:
columns = {'load_id': 'load_id',
            'no_of_dependents': 'no_of_dependents',
            'income_annum': 'income_annum',
            'loan_amount': 'loan_amount',
            'loan_term': 'loan_term',
            'cibil_score': 'cibil_score',
            'residential_assets_value': 'residential_assets_value',
            'commercial_assets_value': 'commercial_assets_value',
            'luxury_assets_value': 'luxury_assets_value',
            'bank_asset_value': 'bank_asset_value',
            'education_ Graduate': 'education_Graduate',
            'self_employed_ No': 'self_employed_No',
            'loan_status_ Approved': 'loan_status_Approved',}
df_onehot.rename(columns=columns, inplace=True)

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

X = df_onehot.drop(columns=['loan_status_Approved'])
y = df_onehot['loan_status_Approved']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [46]:
lg= LogisticRegression(max_iter=1000)
lg.fit(X_train, y_train)
accuracy = lg.score(X_test, y_test)
print(f'Logistic Regression Accuracy: {accuracy:.4f}')

Logistic Regression Accuracy: 0.8197

In [48]:
y_pred = lg.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.82      0.66      0.73       318
        True       0.82      0.92      0.86       536

    accuracy                           0.82       854
   macro avg       0.82      0.79      0.80       854
weighted avg       0.82      0.82      0.81       854

[[209 109]
 [ 45 491]]

In [49]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
rf_accuracy = rf.score(X_test, y_test)
print(f'Random Forest Accuracy: {rf_accuracy:.4f}')

Random Forest Accuracy: 0.9801

In [51]:
y_pred = rf.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.98      0.97      0.97       318
        True       0.98      0.99      0.98       536

    accuracy                           0.98       854
   macro avg       0.98      0.98      0.98       854
weighted avg       0.98      0.98      0.98       854

[[308  10]
 [  7 529]]